- hosts: lanhost
  vars:
    fog_dhcp_server: 172.16.0.1
  tasks:
    - name: Create a group for FOG
      group:
        name: fog-server
        state: present

    - name: Create a user for FOG
      user:
        name: "{{ fog_user }}"
        shell: /bin/bash
        group: fog-server
        append: yes
        createhome: yes

    - name: Create directory Fog
      file:
        path: "/home/{{ fog_user }}/fog"
        owner: "{{ fog_user }}"
        state: directory

# Xóa biến fog_user trên "temp_settings.j2"
    - name: Write temp settings/answer file for FOG
      template:
        src: /root/install-Fog/temp_settings.j2
        dest: "/home/{{ fog_user }}/temp_setting"
        owner: "{{ fog_user }}"

    - name: Install app service
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - wget
          - tar

    - name: wget get link fog.sh
      get_url:
        url: "https://github.com/FOGProject/fogproject/archive/1.5.9.tar.gz"
        dest: /root/1.5.9.tar.gz

    - name: Giai nen
      unarchive:
        src: /root/1.5.9.tar.gz
        dest: /root/
        remote_src: yes

    - name: Stop & Disable FW
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: disable selinux
      selinux:
        policy: targeted
        state: disabled

    - name: Run install Fog
      command: "./installfog.sh -Y -f /home/{{ fog_user }}/temp_setting"
      args:
        chdir: "/root/fogproject-1.5.9/bin"
      become_user: "{{ fog_user }}"
